/**:
  ros__parameters:
    robot_description_planning:
      default_velocity_scaling_factor: 0.1
      default_acceleration_scaling_factor: 0.1
      joint_limits:
        axis_1:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_2:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_3:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_4:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_5:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_6:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
        axis_7:
          has_velocity_limits: true
          max_velocity: 7.5
          has_acceleration_limits: true
          max_acceleration: 0.5
